from model.vitgcn_model import VisionTransformerGCN
from model.label_smothing import LabelSmoothSoftmaxCEV1
from model.vit_model import VisionTransformer
from model.vit_model_wo_token import VisionTransformer_wo_token